name    'ghoneycutt-nsswitch'
version '1.1.0'
source 'git://github.com/ghoneycutt/puppet-module-nsswitch.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage nsswitch'
description 'Manage nsswitch. Supports LDAP integration.'
project_page 'https://github.com/ghoneycutt/puppet-module-nsswitch'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
