name    'ghoneycutt-pam'
version '2.0.0'
source 'git://github.com/ghoneycutt/puppet-module-pam.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage PAM'
description 'Manages PAM, including specifying users and groups in access.conf'
project_page 'https://github.com/ghoneycutt/puppet-module-pam'

dependency 'ghoneycutt/nsswitch', '>= 0.0.1'
