name    'ghoneycutt-pam'
version '2.9.0'
source 'git://github.com/ghoneycutt/puppet-module-pam.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage PAM'
description 'Manages PAM, including specifying users and groups in access.conf, limits.conf, and limits fragments'
project_page 'https://github.com/ghoneycutt/puppet-module-pam'

dependency 'ghoneycutt/common',   '>= 1.0.2'
dependency 'ghoneycutt/nsswitch', '>= 1.1.0'
dependency 'puppetlabs/stdlib',   '>= 3.2.0'
